package com.piggyplugins.BobTheFarmer;

//Main state machine states
public enum State {
    OFF,
    ANIMATING,
    TIMEOUT,

    //Herb runs
    RESTOCK_HERB,
    HERB_TRAVEL_ARDOUGNE,
    HERB_ARDOUGNE,
    ALLOTMENT_ARDOUGNE_1,
    ALLOTMENT_ARDOUGNE_2,
    HERB_TRAVEL_FALADOR,
    HERB_FALADOR,
    ALLOTMENT_FALADOR_1,
    ALLOTMENT_FALADOR_2,
    HERB_TRAVEL_CATHERBY,
    HERB_CATHERBY,
    ALLOTMENT_CATHERBY_1,
    ALLOTMENT_CATHERBY_2,
    HERB_TRAVEL_PORT_PHASMATYS,
    HERB_PORT_PHASMATYS,
    ALLOTMENT_PORT_PHASMATYS_1,
    ALLOTMENT_PORT_PHASMATYS_2,
    HERB_TRAVEL_HOSIDIUS,
    HERB_HOSIDIUS,
    ALLOTMENT_HOSIDIUS_1,
    ALLOTMENT_HOSIDIUS_2,
    HERB_TRAVEL_FARMING_GUILD,
    HERB_FARMING_GUILD,
    ALLOTMENT_FARMING_GUILD_1,
    ALLOTMENT_FARMING_GUILD_2,

    //Tree runs
    RESTOCK_TREE,
    TREE_TRAVEL_FALADOR,
    TREE_FALADOR,
    TREE_TRAVEL_TAVERLEY,
    TREE_TAVERLEY,
    TREE_TRAVEL_VARROCK,
    TREE_VARROCK,
    TREE_TRAVEL_LUMBRIDGE,
    TREE_LUMBRIDGE,
    TREE_TRAVEL_GNOME_STRONGHOLD,
    TREE_GNOME_STRONGHOLD,
    TREE_TRAVEL_FARMING_GUILD,
    TREE_FARMING_GUILD
}

