package com.piggyplugins.BobTheFarmer;

//Main state machine states
public enum State {
    OFF,
    ANIMATING,
    TIMEOUT,

    //Herb runs
    RESTOCK_HERB,
    HERB_TRAVEL_ARDOUGNE,
    HERB_ARDOUGNE,
    HERB_TRAVEL_FALADOR,
    HERB_FALADOR,
    HERB_TRAVEL_CATHERBY,
    HERB_CATHERBY,
    HERB_TRAVEL_PORT_PHASMATYS,
    HERB_PORT_PHASMATYS,
    HERB_TRAVEL_HOSIDIUS,
    HERB_HOSIDIUS,
    HERB_TRAVEL_FARMING_GUILD,
    HERB_FARMING_GUILD,

    //Tree runs
    RESTOCK_TREE,
    TREE_TRAVEL_FALADOR,
    TREE_FALADOR,
    TREE_TRAVEL_TAVERLEY,
    TREE_TAVERLEY,
    TREE_TRAVEL_VARROCK,
    TREE_VARROCK,
    TREE_TRAVEL_LUMBRIDGE,
    TREE_LUMBRIDGE,
    TREE_TRAVEL_GNOME_STRONGHOLD,
    TREE_GNOME_STRONGHOLD,
    TREE_TRAVEL_FARMING_GUILD,
    TREE_FARMING_GUILD
}

